name: Release Pipeline
run-name: ${{ github.actor }} is building a new version 🚀
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-release-version:
    runs-on: ubuntu-latest
    name: Build release version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Release
        uses: mikepenz/release-changelog-builder-action@v5 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}